### PR TITLE
Remove frontend tests from CI

### LINKED ISSUE #24: Delete CI frontend jobs
- [X] I have searched the [issues](https://github.com/Marketing-Automation-Systems/jellyfish/issues/) of this repository and believe that this is not a duplicate.

**Describe the bug 🐛**

Since the frontend will be removed from this project the frontend tests will always fail.

**To Reproduce**
Steps to reproduce the behavior 😯:
1. Go to GitHub Actions
2. Click on any new Event
3. See the error on `npm` steps

**Expected behavior  🤔**

All the CI tests pass.

** How to solve it? **
The suggestion to solve the problem is to remove all CI steps for frontend tests.

**Your environment:**
 - OS: Ubutntu 18.04

### PR DESCRIPTION
**Pull request by lucaslovato**
[X] I have searched the [PR](https://github.com/Marketing-Automation-Systems/jellyfish/pulls/) of this repository and believe that this is not a duplicate.

**Describe the PR**

This PR closes #24 

A new `sln` file was created without the frontend `.csproj's`. With this, the pipeline will pass and the process of removing frontend from Jellyfish can keep going.

**To Reproduce what was done**
1. Go to GitHub actions
2. Click on this [commit](https://github.com/Marketing-Automation-Systems/jellyfish/commit/60e1ba6439a3e2af6c6133a38423d12443f67a9c)
3. See the file changes

### CODE REVIEW

File: ci.sh [hunk 1]
```diff
@@ -9,29 +9,17 @@ sudo /bin/bash -c 'echo -e "127.0.0.1 analytics_platform" >> /etc/hosts'
 # check versions
 dotnet --info
 node --version
```
Comment (leonardo-brickabode) [inline ci.sh]: We also can remove the node --version
```suggestion

```
